version: '3.8'

services:
  typecast-sdk-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    command: /bin/bash
    stdin_open: true
    tty: true