services:
  typecast-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - uv-cache:/root/.cache/uv
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  uv-cache: